_target_: neural_signatures_2.data_modules.synthetic_data_modules.SyntheticSurfaceDataModule
train_dataset_specification:
  _target_: neural_signatures_2.data_modules.synthetic_data_modules.DatasetSpecification
  dataset:
    _target_: neural_signatures_2.datasets.synthetic_datasets.PolynomialSurfaceDataset
    epoch_size: ${globals.train_epoch_size}
    grid_points_count: ${globals.grid_points_count}
    grid_radius_range: ${globals.grid_radius_range}
    grid_offset_range: ${globals.grid_offset_range}
    points_scale_range: ${globals.points_scale_range}
    seed: ${globals.seed}
    order_range: ${globals.order_range}
    coefficient_scale_range: ${globals.coefficient_scale_range}
    coeff_generation_method: ${globals.coeff_generation_method}
  batch_size: ${globals.train_batch_size}
  num_workers: ${globals.train_num_workers}
  shuffle: True
val_dataset_specifications: null

