seed: 42
grid_points_count: 40000
order_range: [2, 7]

grid_radius_range: [1.0]
grid_offset_range: [0.0]
coefficient_scale_range: [0.99, 1.01]
points_scale_range: [1.0]

coeff_generation_method:
  _target_: neural_signatures_2.datasets.synthetic_datasets.CoeffGenerationMethod
  _args_: ['uniform']
